name: Feature branch validation
on:
    push:
        branches:
            - 'feature/**'

permissions:
    contents: read

jobs:
    feature_branch_validation:
        name: Feature Branch validation
        runs-on: ubuntu-22.04
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Gitleaks
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Node setup
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: npm
                cache-dependency-path: api/package-lock.json

            - name: Install dependencies
              working-directory: ./api
              run: npm ci
            - name: ESLINT
              working-directory: ./api
              run: npm run lint
            - name: Prettier
              working-directory: ./api
              run: npx prettier --check
            - name: Audit dependencies
              working-directory: ./api
              run: npm audit --audit-level=high
